### ISSUE TITLE
Test failures don't cause CI failure

### ISSUE THREAD

**Issue by xobs** [antmicro/usb-test-suite-testbenches#13]
The test suite is supposed to run a whole suite of tests in order to ensure the USB stack is still sane.

However, even if a test fails, the whole test suite will still pass. For example: https://travis-ci.com/github/im-tomu/valentyusb/jobs/336431866

**Comment by rkapuscik** [comment]
This is intentional, as the test suite is supposed to be run in CI against different IP cores, that would fail different tests, so setting expected failures for each of them would be impractical.

When running the tests against a single core you could examine the generated `results.xml` file - this is standard jUnit output - to check for regressions. Would that be valid for your case?

**Comment by xobs** [comment]
I can look for the string `"failures"` in `results.xml`, and I'll add the following to my `.travis.yml`:

```
make PYTHONPATH=../litex:../.. TARGET=$T TEST_SCRIPT=$S $OP && ! grep -q failure results.xml
```

It seems a little messy to rely on grep that way.  Why would different cores fail on different tests?  Wouldn't those cores simply not run those tests inside their `tests/` script?

**Comment by rkapuscik** [comment]
I am a bit surprised that I cannot find any relevant option in the cocotb itself. I agree it's not the cleanest solution, but it seems that Travis does not intend to support jUnit output (https://github.com/travis-ci/travis-ci/issues/239)

> Why would different cores fail on different tests? Wouldn't those cores simply not run those tests inside their tests/ script?

The test suite was developed with the intention to test multiple cores on the same set of tests, as it is done in [this parent repository](https://github.com/antmicro/usb-test-suite-build). It turns out most cores have some problems with certain tests. We want to see those results and failures, but do not want them to fail the CI itself (that is reserved to i.e. build errors). This is different than using the test suite as part of IP core development, which is great to see as well.

**Comment by xobs** [comment]
Thanks. I hadn't heard of jUnit, nor could I find any opinion from Travis-CI about its use.

Since it's an issue with upstream cocotb, I'll close this issue here and keep my workaround in place.
